# Generated by Django 6.0.6 on 2026-06-12 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mssql', 'SQL Server'), ('sqlite', 'SQLite')], default='postgresql', max_length=20)),
                ('store_credentials', models.BooleanField(default=True)),
                ('connection_string', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.CharField(blank=True, max_length=10)),
                ('db_name', models.CharField(blank=True, max_length=255)),
                ('db_user', models.CharField(blank=True, max_length=255)),
                ('db_password', models.TextField(blank=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('schema_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('user', 'label')},
            },
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('generated_sql', models.TextField(blank=True)),
                ('nl_response', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='app.databaseconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
