# Generated by Django 6.0.6 on 2026-06-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='fetched_schema',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='schema_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
