# Generated by Django 6.0.6 on 2026-06-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_databaseconnection_fetched_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='is_file_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='sqlite_path',
            field=models.TextField(blank=True),
        ),
    ]
