# Generated by Django 6.0.6 on 2026-06-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_llmprovider_llmmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama (local)')], max_length=20),
        ),
    ]
