# Generated by Django 6.0.6 on 2026-06-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_dashboardchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama (local)')], max_length=20)),
                ('display_name', models.CharField(help_text="Human label, e.g. 'OpenRouter Free Pool #1'", max_length=100)),
                ('api_key', models.TextField(help_text='The actual API key — shown masked to users')),
                ('base_url', models.CharField(blank=True, help_text='Only for Ollama — base URL', max_length=255)),
                ('model_ids', models.TextField(help_text='Comma-separated model IDs available with this key, e.g. google/gemma-3-27b-it:free,deepseek/deepseek-chat-v3-0324:free')),
                ('model_names', models.TextField(blank=True, help_text='Comma-separated display names matching the same order as model_ids')),
                ('note', models.CharField(blank=True, help_text="Short note shown to users, e.g. 'Rate limit: 20 req/min'", max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Community Key',
                'verbose_name_plural': 'Community Keys',
                'ordering': ['provider', 'display_name'],
            },
        ),
    ]
